# Write your MySQL query statement below
SELECT PROJECT_ID,ROUND(AVG(EXPERIENCE_YEARS),2) average_years FROM PROJECT P1
LEFT JOIN EMPLOYEE E1
ON P1.EMPLOYEE_ID=E1.EMPLOYEE_ID
WHERE EXPERIENCE_YEARS IS NOT NULL
GROUP BY PROJECT_ID
